title: pyKT
logo: /assets/img/logo.png
description: A Python Library to Benchmark Deep Learning based Knowledge Tracing Models.
show_downloads: false
theme: jekyll-theme-minimal

include:
  [
    _static,
    _modules,
    _sources
  ]